# Generated by Django 5.2.7 on 2025-11-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(max_length=100, unique=True)),
                ('ensembl_id', models.CharField(blank=True, max_length=50)),
                ('log2fc', models.FloatField(null=True)),
                ('fdr', models.FloatField(null=True)),
                ('pv_enrichment', models.FloatField(null=True)),
                ('cluster', models.CharField(blank=True, max_length=100)),
                ('pathway', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
