# Generated by Django 5.2.7 on 2025-11-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gene',
            old_name='description',
            new_name='Drugs_AB',
        ),
        migrations.RenameField(
            model_name='gene',
            old_name='ensembl_id',
            new_name='ENSEMBL',
        ),
        migrations.RenameField(
            model_name='gene',
            old_name='fdr',
            new_name='adjP',
        ),
        migrations.RenameField(
            model_name='gene',
            old_name='gene_name',
            new_name='gene',
        ),
        migrations.RenameField(
            model_name='gene',
            old_name='log2fc',
            new_name='log2FC',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='pathway',
        ),
        migrations.AddField(
            model_name='gene',
            name='Drugs_Antibody_drug_conjugate',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='Drugs_Enzyme',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='Drugs_OC',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='Drugs_PR',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='Drugs_SM',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='Drugs_Unknown',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='ENTREZID',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gene',
            name='Human_ENSEMBL',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gene',
            name='nonpv_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='pathways',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='pv_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='tract_AB',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='tract_OC',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='tract_PR',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='tract_SM',
            field=models.TextField(blank=True),
        ),
    ]
