# Generated by Django 5.2.7 on 2025-11-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg_app', '0002_rename_description_gene_drugs_ab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='gene',
            field=models.CharField(max_length=100),
        ),
    ]
