# Generated by Django 5.2.7 on 2025-12-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg_app', '0003_alter_gene_gene'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='Mouse_GO_ID',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
