# Generated by Django 5.2.7 on 2025-12-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg_app', '0004_gene_mouse_go_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='gene_description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
