# Generated by Django 5.2.7 on 2025-12-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg_app', '0005_gene_gene_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='gene_description',
            field=models.TextField(blank=True),
        ),
    ]
