# Generated by Django 5.2.7 on 2025-12-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg_app', '0006_alter_gene_gene_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='BipEx_significant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gene',
            name='Disease_hit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gene',
            name='Epi25_significant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gene',
            name='SCHEMA_significant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gene',
            name='SFARI_significant',
            field=models.BooleanField(default=False),
        ),
    ]
